#users = [1200, 2400, 3600, 4800, 6000, 7200, 8400, 9600]
users = [200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000, 2200, 2400]

prefixOPT = '../lotos/output/11_SEG/RES_10S_FINAL/LOTOS/default_config/ite1/SIMRESULT_TWO_TIER_WITH_EO_LOTOS_'
prefixFuzzy = '../fuzzy/output/11_SEG/RES_10S_FINAL/FUZZY_BASED/default_config/ite1/SIMRESULT_TWO_TIER_WITH_EO_FUZZY_BASED_'
prefixUTIL = '../fuzzy/output/11_SEG/RES_10S_FINAL/UTILIZATION_BASED/default_config/ite1/SIMRESULT_TWO_TIER_WITH_EO_UTILIZATION_BASED_'
prefixCOST = '../fuzzy/output/11_SEG/RES_10S_FINAL/MIN_COST/default_config/ite1/SIMRESULT_TWO_TIER_WITH_EO_MIN_COST_'


prefixOPT_SEC = '../lotos/output/11_SEG/RES_10S_SEC_SCEN/LOTOS/default_config/ite1/SIMRESULT_TWO_TIER_WITH_EO_LOTOS_'
prefixFuzzy_SEC = '../fuzzy/output/11_SEG/RES_10S_SEC_SCEN/FUZZY_BASED/default_config/ite1/SIMRESULT_TWO_TIER_WITH_EO_FUZZY_BASED_'
prefixUTIL_SEC = '../fuzzy/output/11_SEG/RES_10S_SEC_SCEN/UTILIZATION_BASED/default_config/ite1/SIMRESULT_TWO_TIER_WITH_EO_UTILIZATION_BASED_'
prefixCOST_SEC = '../fuzzy/output/11_SEG/RES_10S_SEC_SCEN/MIN_COST/default_config/ite1/SIMRESULT_TWO_TIER_WITH_EO_MIN_COST_'



app = ['AUGMENTED_REALITY_GENERIC', 'HEALTH_APP_GENERIC', 'HEAVY_COMP_APP_GENERIC', 'INFOTAINMENT_APP_GENERIC']

time = '../../LOTOS/solution/'

